In [1]:
import numpy as np

In [2]:
##### Create the Array

In [3]:
x = np.array([12,34,5,6,78,])

In [4]:
print(x)

[12 34  5  6 78]


In [5]:
type(x)

numpy.ndarray

In [6]:
x.ndim

1

In [7]:
x

array([12, 34,  5,  6, 78])

In [8]:
x.dtype

dtype('int32')

In [11]:
x = np.array([10,20,30,40,71,60],dtype=np.int8)

In [12]:
x[0] = 200

C:\Users\rajesh\AppData\Local\Temp\ipykernel_4728\3874969223.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x[0] = 200


In [13]:
x

array([-56,  20,  30,  40,  71,  60], dtype=int8)

In [16]:
x = np.array([10,20,30,40,71,60],dtype=np.uint8)

In [17]:
x[0] = 200

In [18]:
x

array([200,  20,  30,  40,  71,  60], dtype=uint8)

In [19]:
x.size

6

In [20]:
x.shape

(6,)

In [21]:
x.min()

20

In [22]:
x.mean()

70.16666666666667

In [23]:
x.sort()

In [24]:
x

array([ 20,  30,  40,  60,  71, 200], dtype=uint8)

In [25]:
x.std()

60.55415390834517

In [26]:
x.sum()

421

In [28]:
x.transpose()

array([ 20,  30,  40,  60,  71, 200], dtype=uint8)

In [29]:
y = np.array([67,12,25,23,45.94])

In [30]:
y

array([67.  , 12.  , 25.  , 23.  , 45.94])

In [31]:
y.dtype

dtype('float64')

In [32]:
print(y[1])

12.0


In [33]:
z = np.array([67,12,25,23,True])

In [34]:
z

array([67, 12, 25, 23,  1])

In [35]:
z = np.array([67,12,25,23,False])

In [36]:
z

array([67, 12, 25, 23,  0])

In [37]:
z = np.array([67,12,25,23,'x'])

In [38]:
z

array(['67', '12', '25', '23', 'x'], dtype='<U11')

In [40]:
z = np.zeros(10,dtype = np.int16)

In [41]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [42]:
y = np.ones(10,dtype = np.int16)

In [43]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [45]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [46]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [47]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [48]:
np.arange(0,10,0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [49]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [55]:
##### Array Operations

In [51]:
num1 = np.array([56,12,56,47,89,23])
num2 = np.array([56,23,36,47,89,23])

In [52]:
num1 + 10

array([66, 22, 66, 57, 99, 33])

In [53]:
num2 /5

array([11.2,  4.6,  7.2,  9.4, 17.8,  4.6])

In [54]:
num1 *4

array([224,  48, 224, 188, 356,  92])

In [56]:
[56,12,56,47,89,23] * 3

[56, 12, 56, 47, 89, 23, 56, 12, 56, 47, 89, 23, 56, 12, 56, 47, 89, 23]

In [57]:
num1 +num2

array([112,  35,  92,  94, 178,  46])

In [58]:
num1 - num2

array([  0, -11,  20,   0,   0,   0])

In [59]:
##### Matrix

In [61]:
m = np.array([[4,6,7],
              [1,2,3],
              [8,0,2],
              [9,3,5]])
             

In [62]:
m

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [63]:
m.dtype

dtype('int32')

In [64]:
m.shape

(4, 3)

In [65]:
m.size

12

In [66]:
m.ndim

2

In [68]:
m[1][1]

2

In [69]:
m[1,1]

2

In [72]:
m[1:3, 1:3]

array([[2, 3],
       [0, 2]])

m1 = m.reshape(1,2)

In [74]:
m1 = m.reshape(6,2)

In [75]:
m1

array([[4, 6],
       [7, 1],
       [2, 3],
       [8, 0],
       [2, 9],
       [3, 5]])

In [76]:
m.reshape(2,-1)

array([[4, 6, 7, 1, 2, 3],
       [8, 0, 2, 9, 3, 5]])

In [77]:
m.reshape(-1,4)

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [2, 9, 3, 5]])

In [79]:
m.reshape(-1)

array([4, 6, 7, 1, 2, 3, 8, 0, 2, 9, 3, 5])

In [80]:
m.flatten()

array([4, 6, 7, 1, 2, 3, 8, 0, 2, 9, 3, 5])

In [81]:
m.T

array([[4, 1, 8, 9],
       [6, 2, 0, 3],
       [7, 3, 2, 5]])

In [82]:
m

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [83]:
m.min()

0

In [84]:
m.min(axis = 1)

array([4, 1, 0, 3])

In [85]:
m.min(axis = 0)

array([1, 0, 2])

In [86]:
m.sum(axis = 0)

array([22, 11, 17])

In [87]:
m.sum(axis = 1)

array([17,  6, 10, 17])

In [88]:
m.sum()

50

In [89]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [91]:
num2.reshape(3,2)

array([[56, 23],
       [36, 47],
       [89, 23]])

In [92]:
m.argmax()

9

In [93]:
m

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [94]:
m = m.astype(np.int16)

In [95]:
m

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]], dtype=int16)

In [96]:
m = m.astype(np.float16)

In [97]:
m

array([[4., 6., 7.],
       [1., 2., 3.],
       [8., 0., 2.],
       [9., 3., 5.]], dtype=float16)

In [98]:
x

array([ 20,  30,  40,  60,  71, 200], dtype=uint8)

In [99]:
id(x)

2045848336784

In [100]:
y = x

In [101]:
id(y)

2045848336784

In [102]:
x[0] = 40

In [103]:
y

array([ 40,  30,  40,  60,  71, 200], dtype=uint8)

In [104]:
y = x.copy()

In [105]:
y

array([ 40,  30,  40,  60,  71, 200], dtype=uint8)

In [106]:
x[0] = 90

In [107]:
x

array([ 90,  30,  40,  60,  71, 200], dtype=uint8)

In [108]:
y

array([ 40,  30,  40,  60,  71, 200], dtype=uint8)

In [109]:
id(x)

2045848336784

In [110]:
id(y)

2045851866224