In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [3]:
pip install tensorflow -U

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install tensorflow -U

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf

In [2]:
#### Create Tensors

In [3]:
a = tf.constant([1,2,3])
b =  tf.constant([4,5,6])
print('Tensor a:',a)
print('Tensor b:',b)

Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [4]:
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
x = tf.constant([[1,2,3],[7,8,9]])
y =  tf.constant([[4,5],[6,7]])
print('Tensor x:',x)
print('Tensor y:',y)

Tensor x: tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)
Tensor y: tf.Tensor(
[[4 5]
 [6 7]], shape=(2, 2), dtype=int32)


In [13]:
x = tf.constant([[1,2,3],[7,8,9],[2,5,6],[9,5,4]])
y =  tf.constant([[4,5],[6,7]])
print('Tensor x:',x)
print('Tensor y:',y)

Tensor x: tf.Tensor(
[[1 2 3]
 [7 8 9]
 [2 5 6]
 [9 5 4]], shape=(4, 3), dtype=int32)
Tensor y: tf.Tensor(
[[4 5]
 [6 7]], shape=(2, 2), dtype=int32)


In [14]:
# Add Tensor
c = tf.add(a,b)
print ('Tensor c',c)

Tensor c tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [15]:
a -b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [21]:
d = tf.subtract(b,a)
print ('Tensor d',d)

Tensor d tf.Tensor([3 3 3], shape=(3,), dtype=int32)


In [22]:
d.numpy()

array([3, 3, 3])

In [23]:
e= tf.multiply(a,b)
print ('Tensor d',e)

Tensor d tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [24]:
a *b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [25]:
f= tf.divide(a,b)
print ('Tensor d',f)

Tensor d tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [26]:
a//b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [27]:
6//3

2

In [28]:
6.5/3.5

1.8571428571428572

In [29]:
6.5//3.5

1.0

In [32]:
#Matrix Multiplication
a_matrix = tf.constant([[1,2],[3,4]])
b_matrix = tf.constant([[5,6],[7,8]])
g = tf.matmul(a_matrix,b_matrix)
print('Multiplication Result',g)

Multiplication Result tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
